import { Component, EventEmitter, Output } from '@angular/core';
import { ToDo } from 'ToDo';
import { TodoService } from '../todo.service';

@Component({
  selector: 'app-add',
  templateUrl: './add.component.html',
  styleUrls: ['./add.component.css']
})
export class AddComponent {
  task: ToDo = {
    id: { taskId: 0, userId: 0 }, // Corrected nested id structure
    taskName: '',
    taskDescription: '',
    taskStatus: 'Pending'
  };

  @Output() taskAdded = new EventEmitter<void>();

  constructor(private todoService: TodoService) {}

  onSubmit(): void {
    const userIdStr = sessionStorage.getItem('userId');
    console.log('👉 User ID from sessionStorage:', userIdStr);  // 🧪 Should print a number string
  
    const userId = userIdStr ? Number(userIdStr) : null;
  
    if (!userId || isNaN(userId)) {
      console.error('❌ Invalid or missing userId in sessionStorage');
      return;
    }
  
    this.task.id.userId = userId; // Set userId inside the id object
  
    // Assuming taskId is generated by the backend or auto-incremented
    this.todoService.addTask(userId, this.task).subscribe(() => {
      this.taskAdded.emit(); // Notify parent component
    }, error => {
      console.error('Error adding task', error);
    });
  }
}  